[project]
name = "project-planner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyterlab>=4.4.1",
    "pydantic-ai>=0.1.9",
]
